# Generated by Django 5.2.6 on 2025-09-15 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('tuition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='tuition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='tuition.tuition'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('tuition', 'student')},
        ),
    ]
